apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Maldev01/online-boutique-gitops'
    targetRevision: main
    path: 'helm-chart'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true