apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-servicemonitor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: 'https://github.com/Maldev01/online-boutique-gitop'
    targetRevision: main
    path: .

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true