# Top-level image configuration your CI will update
images:
  repository: "307857433476.dkr.ecr.us-east-1.amazonaws.com" # CI will set this to <ACCOUNT_ID>.dkr.ecr.<region>.amazonaws.com
  tag: "c098d54b429bc4182915720ed6e63d686dec6b9b" # CI will set this to the image tag (e.g. github sha)
# Services map: add or remove services as needed; CI will not overwrite this section

# CI only updates images.repository and images.tag so the chart will pull images like:

# <images.repository>/<service>:<images.tag>
services:
  frontend:
    port: 8080
    replicas: 2
  productcatalogservice:
    port: 3550
    replicas: 1
  cartservice:
    port: 7070
    replicas: 1
  checkoutservice:
    port: 5050
    replicas: 1
  currencyservice:
    port: 7000
    replicas: 1
  emailservice:
    port: 5000
    replicas: 1
  paymentservice:
    port: 50051
    replicas: 1
  recommendationservice:
    port: 8080
    replicas: 1
  shippingservice:
    port: 50051
    replicas: 1
  adservice:
    port: 9555
    replicas: 1
  shoppingassistantservice:
    port: 8080
    replicas: 1
# Basic resource defaults that templates use (override per-service if you want)
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
